In [104]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import sklearn

/Users/krishrajpal/opt/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [105]:
address_1='/Users/krishrajpal/Documents/SummerAnalytics_Python/Train_Data.csv'
address_2='/Users/krishrajpal/Documents/SummerAnalytics_Python/Test_Data.csv'
Advertisement_Train=pd.read_csv(address_1)
Advertisement_Test=pd.read_csv(address_2)
Advertisement_Train.head(1000)

,date,campaign,adgroup,ad,impressions,clicks,cost,conversions,revenue
0,01-08-2020,campaign 1,adgroup 1,ad 1,24,6,0.08,0,0.00
1,01-08-2020,campaign 1,adgroup 2,ad 1,1,0,0.00,0,0.00
2,01-08-2020,campaign 1,adgroup 3,ad 1,13,4,0.04,0,0.00
3,01-08-2020,campaign 1,adgroup 4,ad 1,5,4,0.08,0,0.00
4,01-08-2020,campaign 1,adgroup 1,ad 2,247,126,1.29,4,925.71
...,...,...,...,...,...,...,...,...,...
995,27-09-2020,campaign 1,adgroup 3,ad 5,95,55,5.44,0,0.00
996,27-09-2020,campaign 1,adgroup 3,ad 6,190,92,7.23,6,1421.59
997,27-09-2020,campaign 1,adgroup 1,ad 7,17,8,0.20,1,96.41
998,27-09-2020,campaign 1,adgroup 2,ad 7,9,3,0.21,0,0.00
999,27-09-2020,campaign 1,adgroup 3,ad 7,17,8,1.44,0,0.00

In [106]:
cols_with_missing = [col for col in Advertisement_Train.columns if Advertisement_Train[col].isnull().any()]
Advertisement_Train.drop(cols_with_missing, axis=1, inplace=True)
Advertisement_Test.drop(cols_with_missing, axis=1, inplace=True)
Advertisement_Train.drop(['date','campaign'], axis=1 ,inplace=True)
Advertisement_Test.drop(['date','campaign'], axis=1 ,inplace=True)
Advertisement_Train.head(15)

/Users/krishrajpal/opt/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

      adgroup    ad  impressions  clicks  cost  conversions  revenue
0   adgroup 1  ad 1           24       6  0.08            0     0.00
1   adgroup 2  ad 1            1       0  0.00            0     0.00
2   adgroup 3  ad 1           13       4  0.04            0     0.00
3   adgroup 4  ad 1            5       4  0.08            0     0.00
4   adgroup 1  ad 2          247     126  1.29            4   925.71
5   adgroup 2  ad 2            7       2  0.04            0     0.00
6   adgroup 4  ad 2            6       3  0.05            0     0.00
7   adgroup 1  ad 3          129      52  0.58            0     0.00
8   adgroup 3  ad 3          104      56  0.56            0     0.00
9   adgroup 4  ad 3            6       5  0.05            0     0.00
10  adgroup 2  ad 3            4       0  0.00            0     0.00
11  adgroup 3  ad 4           39      16  0.22            0     0.00
12  adgroup 3  ad 5           17       6  0.06            0     0.00
13  adgroup 3  ad 6          253     128  1.32            2   339.83
14  adgroup 3  ad 7           16       6  0.07            0     0.00

In [124]:
from sklearn.model_selection import train_test_split
y=Advertisement_Train.revenue
features=['adgroup','ad','impressions','clicks','cost','conversions']
X=Advertisement_Train[features]
X_train,X_valid,y_train,y_valid= train_test_split(X, y,train_size=0.8, test_size=0.2, random_state=0)
X_test = Advertisement_Test[features]

In [125]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import mean_absolute_error
from sklearn.impute import SimpleImputer
def score_dataset(X_train, X_valid, y_train, y_valid):
    RandomForestModel = RandomForestRegressor(n_estimators=10000, random_state=0)
    RandomForestModel.fit(X_train, y_train)
    Predictions = RandomForestModel.predict(X_valid)
    return mean_absolute_error(y_valid, Predictions)

In [122]:
drop_X = X.select_dtypes(exclude=['object'])
drop_X_test = X_test.select_dtypes(exclude=['object'])
RandomForestModel = XGBRegressor(n_estimators=1000, learning_rate=0.05)
RandomForestModel.fit(drop_X,y)
predictions=RandomForestModel.predict(drop_X_test)
print(predictions)
revenue_prediction =pd.DataFrame(predictions)
revenue_prediction.columns = ["revenue"]
revenue_prediction.to_csv('RevenuePredictions12.csv',index=False)

[ 1.20417015e+02  1.30619264e+00  9.71827358e-02  9.71827358e-02
  9.71827358e-02  9.71827358e-02  1.11472130e+02  9.71827358e-02
  2.09832504e+02  1.36097848e-01  2.46274078e+02  9.20420811e-02
 -2.93666720e-01  2.95582153e+02  9.71827358e-02  1.12195160e+02
  2.81126285e+00  1.79420990e+02 -1.02712154e+00  1.52732071e+02
  9.71827358e-02 -6.81874704e+00  9.71827358e-02  3.64871185e+02
  9.71827358e-02  9.71827358e-02  4.37804260e+02  1.99503952e+02
  9.71827358e-02  9.71827358e-02  4.58393219e+02  1.84747919e-01
  6.96779297e+02  3.34910492e+02  1.39367905e+02  9.71827358e-02
  6.79681396e+01 -6.65493250e-01  9.71827358e-02  1.08450517e-01
  2.31007591e-01 -3.54387164e+00  9.71827358e-02 -2.02119684e+00
  7.85614443e+00  9.71827358e-02  9.71827358e-02  9.71827358e-02
 -1.56288028e-01 -2.68954039e-01  9.71827358e-02  1.27868444e-01
  6.50631428e+00  3.09536804e+02  1.56389664e+02  1.66288788e+02
  9.71827358e-02  9.71827358e-02  9.71827358e-02  7.72707581e+02
  9.71827358e-02  2.59970032e+02  9.71827358e-02  3.44616730e+02
  9.71827358e-02 -1.24786615e+00  2.56801483e+02  2.58986786e+02
  9.71827358e-02  9.71827358e-02  2.79154358e+02  9.71827358e-02
  9.71827358e-02  9.71827358e-02  7.85084839e+01  2.39520966e+02
  5.07106995e+02  9.71827358e-02 -4.60558558e+00  1.56434670e-01
  2.27551041e+02  2.32859222e+02 -2.63783813e+00  1.05910027e+02
  1.20631285e-01  9.71827358e-02  5.52673828e+02  1.23958496e+03
  9.71827358e-02  5.17705811e+02  3.43077820e+02  3.53059448e+02
 -4.86082649e+00  6.03431824e+02  1.14609192e+02  9.71827358e-02
  9.71827358e-02  9.71827358e-02  5.12939301e+01  9.71827358e-02
  1.27327278e+02  9.71827358e-02  9.71827358e-02  2.54745941e+02
  9.71827358e-02  1.81293359e+03  9.71827358e-02  3.13470306e+02
  9.71827358e-02  1.55503113e+02  9.71827358e-02  1.00705237e+03
  2.47046202e-01  3.10084167e+02  2.47046202e-01  1.75494873e+03
 -7.48237520e-02  2.02086646e+03  5.41460999e+02  1.52254486e+02
  9.71827358e-02  9.71827358e-02  3.72575928e+02  9.71827358e-02
 -4.11700867e-02  9.71827358e-02  5.51816406e+02  9.71827358e-02
  2.11339005e+02  1.75033112e+02  9.71827358e-02  9.71827358e-02
  2.47046202e-01  1.62007138e-01  5.50964722e+02  1.24286655e-02
 -1.46351242e+00  1.56434670e-01  4.47225372e+02  9.71827358e-02
  2.20616150e+02  9.71827358e-02 -2.93666720e-01  9.71827358e-02
  1.29943390e+02  9.71827358e-02  9.71827358e-02  1.97471069e+02
  4.01225739e+02 -8.46669972e-02  9.71827358e-02  9.71827358e-02
  6.30053040e+02  9.71827358e-02  1.87652237e+02  9.71827358e-02
  6.40211426e+02  9.71827358e-02 -5.28617561e-01  1.62007138e-01
  8.40699081e+01  9.71827358e-02 -4.32141495e+00  1.09255701e-01
  1.80626862e+02  9.71827358e-02  2.51172073e+02 -1.32056022e+00
  9.71827358e-02 -5.53127229e-01  1.62007138e-01  9.71827358e-02
 -3.17835808e+00  1.94184464e+02  9.71827358e-02 -3.37163627e-01
  9.71827358e-02  9.71827358e-02  1.91527985e+02  1.31121429e+02
  9.71827358e-02 -2.08853130e+01  9.71827358e-02  1.48782745e+02
 -1.18084645e+00 -2.22278810e+00  2.92427704e+02  7.31848373e+01
  9.85434799e+01  9.71827358e-02  7.99169846e+01  1.05267860e+02
 -4.86082649e+00 -3.37163627e-01  1.37859711e+02  1.31495297e-01
  9.71827358e-02  9.71827358e-02 -5.28617561e-01  2.02083893e+02
  2.62952118e+02  9.71827358e-02  1.85952866e+02  9.71827358e-02
  9.71827358e-02  1.07463872e+00  1.09242279e+02 -5.53127229e-01
  9.01972950e-01  3.48281128e+02  9.71827358e-02 -1.31633365e+00
 -1.35769296e+00  1.16226891e+02  3.58828979e+02  9.71827358e-02
  3.04157305e+00 -7.48237520e-02 -2.68954039e-01  5.67197144e+02
  9.71827358e-02 -3.37163627e-01  6.26151657e+00  9.71827358e-02
  9.71827358e-02  4.77511200e+02  9.71827358e-02  9.71827358e-02
  2.05806446e+01  9.71827358e-02  3.36659180e+02 -7.01349318e-01
 -1.44266295e+00  4.22820330e+00 -3.40030603e-02  3.61654282e-01
  9.71827358e-02  1.11303383e+02 -3.35615605e-01  2.62690187e+00
  9.71827358e-02  9.71827358e-02 -9.74441707e-01 -2.93666720e-01
  9.71827358e-02  1.60464081e+02  9.71827358e-02 -3.56562018e+00
  9.71827358e-02  9.71827358e-02  5.67658447e+02  1.45236755e+02
  9.71827358e-02  3.96073700e+02  9.71827358e-02  6.63607864e+01
 -8.79740953e-01  2.87036967e+00  1.19942352e+02  9.77218018e+01
  9.71827358e-02  2.45900894e+02 -3.85882926e+00  4.20503693e+01
  9.71827358e-02 -5.28617561e-01 -2.85274553e+00  9.71827358e-02
  9.71827358e-02  9.71827358e-02  3.29783264e+02  9.71827358e-02
 -2.93666720e-01  5.40562195e+02  9.71827358e-02  9.71827358e-02
  9.71827358e-02  2.16728912e+02  1.14627846e+02  9.71827358e-02
 -2.22786099e-01  4.03887212e-01  6.07626438e+00  9.71827358e-02
  2.65923340e+02  5.61969697e-01  1.20106117e+02 -2.56554484e+00
  9.71827358e-02  1.27615213e-01  2.47046202e-01  2.03316223e+02
  8.70919108e-01  9.71827358e-02  1.98109299e+02 -2.68954039e-01
  9.71827358e-02  1.87755035e+02  9.71827358e-02  9.71827358e-02
  9.71827358e-02  9.71827358e-02  5.07226013e+02 -1.10943689e+01
  2.55849749e-01 -7.54218519e-01  5.63488770e+02 -2.03437269e-01
  9.71827358e-02  2.53837570e+02  9.07742691e+01  8.52710342e+01
  9.71827358e-02  9.71827358e-02  9.71827358e-02  3.45227867e-01
  9.71827358e-02  2.35951538e+02]

In [126]:
drop_X_train = X_train.select_dtypes(exclude=['object'])
drop_X_valid = X_valid.select_dtypes(exclude=['object'])
drop_X_test = X_test.select_dtypes(exclude=['object'])
drop_X_train['CTR']=drop_X_train['clicks']/drop_X_train['impressions']
drop_X_train['CPC']=drop_X_train['cost']/drop_X_train['clicks']
drop_X_train['CPA']=drop_X_train['cost']/drop_X_train['conversions']
drop_X_valid['CTR']=drop_X_valid['clicks']/drop_X_valid['impressions']
drop_X_valid['CPC']=drop_X_valid['cost']/drop_X_valid['clicks']
drop_X_valid['CPA']=drop_X_valid['cost']/drop_X_valid['conversions']
drop_X_test['CTR']=drop_X_test['clicks']/drop_X_test['impressions']
drop_X_test['CPC']=drop_X_test['cost']/drop_X_test['clicks']
drop_X_test['CPA']=drop_X_test['cost']/drop_X_test['conversions']
drop_X_train.head(25)

<ipython-input-126-c0b7a7ea1d9c>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  drop_X_train['CTR']=drop_X_train['clicks']/drop_X_train['impressions']
<ipython-input-126-c0b7a7ea1d9c>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  drop_X_valid['CTR']=drop_X_valid['clicks']/drop_X_valid['impressions']
<ipython-input-126-c0b7a7ea1d9c>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  drop_X_test['CTR']=drop_X_test['clicks']/drop_X_test['impressions']

      impressions  clicks   cost  conversions       CTR       CPC        CPA
483           398     188  62.03            7  0.472362  0.329947   8.861429
982           442     212  57.45            1  0.479638  0.270991  57.450000
4101           16       7   0.07            0  0.437500  0.010000        inf
2829           39      17   0.21            0  0.435897  0.012353        inf
2627            9       6   0.07            0  0.666667  0.011667        inf
1746          315     147  19.25            4  0.466667  0.130952   4.812500
1513           21       7   1.29            0  0.333333  0.184286        inf
1953           15       8   1.30            0  0.533333  0.162500        inf
2518            1       0   0.00            0  0.000000       NaN        NaN
3112            8       5   0.10            1  0.625000  0.020000   0.100000
2231           67      39   0.61            2  0.582090  0.015641   0.305000
3582           16       8   1.51            0  0.500000  0.188750        inf
4093           18      10   0.11            1  0.555556  0.011000   0.110000
841             2       3   0.09            0  1.500000  0.030000        inf
2254           19      10   0.79            2  0.526316  0.079000   0.395000
2891            1       1   0.02            0  1.000000  0.020000        inf
1259          351     171   8.35            1  0.487179  0.048830   8.350000
3008           11       2   0.02            0  0.181818  0.010000        inf
2992          147      63   0.84            1  0.428571  0.013333   0.840000
971             4       1   0.01            0  0.250000  0.010000        inf
3473            3       1   0.01            0  0.333333  0.010000        inf
3256           12       8   0.10            0  0.666667  0.012500        inf
871            10       4   0.05            0  0.400000  0.012500        inf
843            86      41   0.45            0  0.476744  0.010976        inf
3970           19      10   0.16            0  0.526316  0.016000        inf

In [127]:
drop_X_train = drop_X_train.replace([np.inf, -np.inf], np.nan)
drop_X_valid = drop_X_valid.replace([np.inf, -np.inf], np.nan)
drop_X_test = drop_X_test.replace([np.inf, -np.inf], np.nan)

/Users/krishrajpal/opt/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [128]:
drop_X_train.drop(['clicks'], axis=1 ,inplace=True)
drop_X_train.head()

      impressions   cost  conversions       CTR       CPC        CPA
483           398  62.03            7  0.472362  0.329947   8.861429
982           442  57.45            1  0.479638  0.270991  57.450000
4101           16   0.07            0  0.437500  0.010000        NaN
2829           39   0.21            0  0.435897  0.012353        NaN
2627            9   0.07            0  0.666667  0.011667        NaN

In [129]:
drop_X_valid.drop(['clicks'], axis=1 ,inplace=True)
drop_X_valid.head()

/Users/krishrajpal/opt/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

      impressions  cost  conversions       CTR       CPC    CPA
773             9  0.03            0  0.333333  0.010000    NaN
2507          233  1.95            0  0.416309  0.020103    NaN
4198          250  2.02            4  0.352000  0.022955  0.505
1596           11  1.75            0  0.727273  0.218750    NaN
3241           29  0.12            0  0.413793  0.010000    NaN

In [130]:
drop_X_test.drop(['clicks'], axis=1 ,inplace=True)
drop_X_test.head()

/Users/krishrajpal/opt/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

   impressions  cost  conversions       CTR       CPC   CPA
0          121  0.58            1  0.404959  0.011837  0.58
1           22  0.17            0  0.545455  0.014167   NaN
2            5  0.05            0  0.600000  0.016667   NaN
3            2  0.01            0  0.500000  0.010000   NaN
4            3  0.01            0  0.333333  0.010000   NaN

In [131]:
# Imputation
my_imputer = SimpleImputer()
imputed_X_train = pd.DataFrame(my_imputer.fit_transform(drop_X_train))
imputed_X_valid = pd.DataFrame(my_imputer.transform(drop_X_valid))
imputed_X_test = pd.DataFrame(my_imputer.transform(drop_X_test))

# Imputation removed column names; put them back
imputed_X_train.columns = drop_X_train.columns
imputed_X_valid.columns = drop_X_valid.columns
imputed_X_test.columns = drop_X_test.columns
print(score_dataset(imputed_X_train, imputed_X_valid, y_train, y_valid))

/Users/krishrajpal/opt/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

69.85388578831821

In [132]:
RandomForestModel = XGBRegressor(n_estimators=1000, random_state=0)
RandomForestModel.fit(imputed_X_train, y_train)
Predictions10 = RandomForestModel.predict(imputed_X_test)
print(Predictions10)

/Users/krishrajpal/opt/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

[ 1.21413635e+02 -1.12678759e-01  5.20577729e-02 -1.37905101e-03
  1.66336261e-03  5.16257342e-03  8.74634323e+01  1.18815135e-02
  7.93763962e+01  2.24375829e-01  2.24109909e+02  3.11910868e-01
 -4.14691061e-01  4.32854828e+02  4.38069168e-04  1.19409668e+02
 -8.57730091e-01  2.43241714e+02  1.13283503e+00  6.62502823e+01
 -1.37853215e-03 -1.12797403e+00  4.38069168e-04  3.32533234e+02
  6.66894484e-05  1.25555717e-03  4.56725525e+02  1.80196899e+02
  8.06444045e-03  6.66894484e-05  5.86599731e+02  2.87068915e-02
  9.21071106e+02  2.08452484e+02  1.39059692e+02 -4.16643918e-03
  9.57894745e+01  7.04711258e-01  6.66894484e-05 -6.37935661e-03
 -2.69321203e-02  6.16260052e-01  6.66894484e-05 -1.25420499e+00
  1.36750662e+00 -1.52757927e-03 -1.74630284e-02  3.56117496e-03
 -3.55351828e-02 -1.51639723e-03  6.66894484e-05  1.54946921e-02
 -3.55738461e-01  2.21710480e+02  9.63186188e+01  5.17411537e+01
  3.42314132e-04 -1.13042993e-02 -1.83128868e-03  1.07028455e+03
  1.66336261e-03  2.60939758e+02  4.40768385e-03  2.42816208e+02
  6.55837264e-03  5.69158745e+00  3.87830383e+02  1.16299561e+02
  3.42314132e-04 -2.18175631e-02  1.11946152e+02 -1.37905101e-03
 -3.19218799e-03  6.66894484e-05  1.18368958e+02  4.28073502e+01
  4.81547119e+02 -1.37905101e-03 -2.01336155e+01  7.18837678e-02
  4.01913269e+02  2.49424988e+02  4.47894871e-01  8.79622498e+01
 -5.20334253e-03  2.30913633e-03  4.29236359e+02  1.08796069e+03
  6.66894484e-05  5.01112518e+02  3.12839569e+02  3.15264618e+02
  1.40228343e+00  7.22071167e+02  9.56921921e+01 -1.52757927e-03
  6.66894484e-05  6.66894484e-05  2.51246300e+01 -1.10543892e-03
  9.55797729e+01  3.42314132e-04 -1.67465601e-02  6.80660782e+01
  3.87877924e-03  1.89589880e+03  2.72986887e-04  2.24645874e+02
  1.87103607e-04  1.26070595e+02  3.12691613e-04  5.93280823e+02
  2.11427175e-02  3.03455536e+02  2.11427175e-02  1.82040601e+03
  1.17595382e-02  1.91052759e+03  4.45754517e+02  1.22583183e+02
  3.87877924e-03  3.56117496e-03  5.16630676e+02  3.81953141e-04
 -3.90999988e-02  6.66894484e-05  3.15038849e+02  5.01566567e-04
  1.43954224e+02  1.81940094e+02  1.87103607e-04  1.87103607e-04
 -3.18066068e-02  1.27271060e-02  7.89160522e+02  1.53711259e-01
  8.27922523e-02 -3.08251325e-02  5.01314117e+02  6.66894484e-05
  1.28320999e+02  6.66894484e-05  1.09270394e-01  3.42314132e-04
  2.00582153e+02  3.42314132e-04 -5.81299560e-03  2.05256363e+02
  6.41563171e+02  8.05626437e-02 -7.12247239e-03  3.12691613e-04
  4.92474579e+02  1.18815135e-02  2.31478668e+02  5.16257342e-03
  7.63099243e+02 -1.62579622e-02 -1.50215551e-01  7.55951554e-03
  1.62981934e+02  6.66894484e-05 -1.86172694e-01 -1.17461093e-01
  2.06755127e+02  6.66894484e-05  4.52956635e+02 -3.43380541e-01
  3.42314132e-04  9.13319826e-01 -1.21117793e-02  6.66894484e-05
 -2.61334915e+01  1.98617996e+02  6.66894484e-05 -1.33288294e-01
  6.66894484e-05 -2.26412690e-03  1.11939445e+02  2.41850189e+02
 -7.17232889e-03  9.57241714e-01  6.66894484e-05  2.36301239e+02
 -3.84432197e-01  3.45950499e-02  1.64881485e+02  1.18667804e-01
  2.27334686e+02  1.66336261e-03  7.14566422e+00  8.37870941e+01
  1.11100543e+00 -6.03394918e-02  2.42438214e-03  3.56670879e-02
  6.66894484e-05  6.66894484e-05 -8.07167470e-01  1.98294647e+02
  1.85920975e+02  4.38069168e-04  1.66289322e+02  7.34810438e-03
  6.66894484e-05  2.34405184e+00  2.57870426e+01  9.83781159e-01
 -4.94225740e-01  2.60048950e+02  4.94976295e-03 -2.58626729e-01
 -2.42495358e-01  1.83022949e+02  3.92921265e+02 -1.16668968e-02
 -2.35596359e-01  5.30604273e-04  5.36510814e-03  4.45683289e+02
  3.12691613e-04  4.47907764e-03  2.45193558e+01  3.42314132e-04
 -3.69236013e-03  6.86186890e+02 -1.16282282e-03  3.81953141e-04
  6.65247345e+01 -1.52757927e-03  3.16395508e+02  1.19016938e-01
 -5.10255098e-01  4.57307930e+01 -1.49679836e-02  6.86596096e-01
  1.87103607e-04  7.65066605e+01  2.25281775e-01 -2.14491114e-01
  6.66894484e-05  4.01996356e-03  1.10529631e-01 -3.39029133e-02
  3.12691613e-04  1.12006714e+02 -1.52757927e-03 -7.01653290e+00
  5.16257342e-03  6.66894484e-05  4.28359680e+02  1.53177002e+02
  3.87877924e-03  5.72286255e+02  1.87103607e-04 -2.66487293e+01
 -1.99227128e-02  6.02460098e+00  3.23970528e+01  4.59281807e+01
 -2.26412690e-03  1.37467331e+02 -6.69792533e-01  2.04972458e+01
  1.87103607e-04  2.55277473e-02 -4.28549141e-01  1.42700672e-02
  3.12691613e-04  3.87877924e-03  3.43531464e+02  6.66894484e-05
  2.28021238e-02  4.59747223e+02  4.38069168e-04  3.56117496e-03
 -8.98895487e-02  2.07320679e+02  1.26090324e+02  3.87877924e-03
 -1.15129314e-01  4.29987572e-02 -8.81082153e+00  6.66894484e-05
  2.23633911e+02 -2.87822308e-03  6.25070305e+01  9.41232026e-01
  6.66894484e-05  7.78618595e-03 -4.57684249e-02  8.51698303e+01
  7.78204918e-01  4.94976295e-03  2.12302673e+02 -8.18180293e-02
 -1.16282282e-03  2.13674866e+02 -1.37905101e-03  3.12691613e-04
  3.42314132e-04 -2.29596011e-02  5.38703430e+02 -3.70246277e+01
 -1.07131805e+01 -3.54679190e-02  7.31847046e+02  9.20130014e-01
  1.44023150e-02  1.65117157e+02  1.02864929e+02  2.71084328e+01
  6.66894484e-05  3.42314132e-04 -1.10543892e-03  2.49316767e-01
 -1.04774661e-01  2.99101990e+02]

In [133]:
revenue_prediction =pd.DataFrame(Predictions10)
revenue_prediction.columns = ["revenue"]
revenue_prediction.to_csv('RevenuePredictions12.csv',index=False)

In [32]:
from hyperopt import fmin, tpe, rand, hp, Trials, STATUS_OK
import xgboost
from xgboost import XGBRegressor
from sklearn.model_selection import cross_val_score
import mlflow

/Users/krishrajpal/opt/anaconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [34]:
def train(params):
        """
        An example train method that computes the square of the input.
        This method will be passed to `hyperopt.fmin()`.
        
        :param params: hyperparameters. Its structure is consistent with how search space is defined. See below.
        :return: dict with fields 'loss' (scalar loss) and 'status' (success/failure status of run)
        """
        curr_model =  XGBRegressor(learning_rate=params[0],
                                gamma=int(params[1]),
                                max_depth=int(params[2]),
                                n_estimators=int(params[3]),
                                min_child_weight = params[4], objective='reg:squarederror')
        score = -cross_val_score(curr_model, X_train, y_train, scoring='neg_mean_squared_error').mean()
        score = np.array(score)
        
        return {'loss': score, 'status': STATUS_OK, 'model': curr_model}
    
    
    # define search parameters and whether discrete or continuous
search_space = [ hp.uniform('learning_rate', 0, 1),
                        hp.uniform('gamma', 0, 5),
                        hp.randint('max_depth', 10),
                        hp.randint('n_estimators', 20),
                        hp.randint('min_child_weight', 10)
                    ]
    # define the search algorithm (TPE or Randomized Search)
    algo= tpe.suggest
    
from hyperopt import SparkTrials
search_parallelism = 4
spark_trials = SparkTrials(parallelism=search_parallelism)
    
with mlflow.start_run():
        argmin = fmin(
        fn=train,
        space=search_space,
        algo=algo,
        max_evals=8,
        trials=spark_trials)
    
    
    def fit_best_model(X, y): 
        client = mlflow.tracking.MlflowClient()
        experiment_id = client.get_experiment_by_name(experiment_name).experiment_id
    
        runs = mlflow.search_runs(experiment_id)
        best_loss = runs['metrics.loss'].min()
        best_run=runs[runs['metrics.loss'] == best_loss]
    
        best_params = {}
        best_params['gamma'] = float(best_run['params.gamma'])
        best_params['learning_rate'] = float(best_run['params.learning_rate'])
        best_params['max_depth'] = float(best_run['params.max_depth'])
        best_params['min_child_weight'] = float(best_run['params.min_child_weight'])  
        best_params['n_estimators'] = float(best_run['params.n_estimators'])
        
        xgb_regressor =  XGBRegressor(learning_rate=best_params['learning_rate'],
                                max_depth=int(best_params['max_depth']),
                                n_estimators=int(best_params['n_estimators']),
                                gamma=int(best_params['gamma']),
                                min_child_weight = best_params['min_child_weight'], objective='reg:squarederror')
    
        xgb_model = xgb_regressor.fit(X, y, verbose=False)
    
        return(xgb_model)
    
    # fit model using best parameters and log the model
    xgb_model = fit_best_model(X_train, y_train) 
    mlflow.xgboost.log_model(xgb_model, "xgboost") # log the model here 
    
    
    from sklearn.metrics import r2_score
    from sklearn.metrics import mean_squared_error
    train_pred = xgb_model.predict(X_train)
    test_pred = xgb_model.predict(X_test)

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 21)